notification:
    email: false

language: C++

os:
    - linux

before_install:
    - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
    - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}
    - sudo apt-get update
    ####################################
    # install latest arm-none-eabi-gcc #
    ####################################
    - ARM_GCC_URL="https://developer.arm.com/-/media/Files/downloads/gnu-rm/9-2019q4/gcc-arm-none-eabi-9-2019-q4-major-x86_64-linux.tar.bz2?revision=108bd959-44bd-4619-9c19-26187abf5225&la=en&hash=E788CE92E5DFD64B2A8C246BBA91A249CB8E2D2D"
    - mkdir arm-gcc && travis_retry wget --quiet -O - ${ARM_GCC_URL} | tar --strip-components=1 -xj -C arm-gcc
    - export PATH="${DEPS_DIR}/arm-gcc/bin:${PATH}"
    - arm-none-eabi-gcc --version
    - arm-none-eabi-ld --version
    ####################################
    # install latest cmake             #
    ####################################
    - CMAKE_URL="https://github.com/Kitware/CMake/releases/download/v3.17.0-rc1/cmake-3.17.0-rc1-Linux-x86_64.tar.gz"
    - mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
    - export PATH="${DEPS_DIR}/cmake/bin:${PATH}"
    - cmake --version
    ####################################
    # install PyYAML                   #
    ####################################
    - sudo apt-get install python3 python3-pip
    - pip3 install --upgrade pip
    - pip3 install pyyaml
addons:
    apt:
        sources:
        - deadsnakes
        packages:
        - python3.8
script:
    - cd $TRAVIS_BUILD_DIR
    - mkdir build && cd build
    - cmake -DBUILD_EXAMPLE=ON -DTARGET_BOARD="stm32f446re" -G "Unix Makefiles" ..
    - cmake --build ./
    ###################################
    # build target board stm32l432kc  #
    ###################################
    - cmake -DBUILD_EXAMPLE=ON -DTARGET_BOARD="stm32l432kc" -G "Unix Makefiles" ..
    - cmake --build ./
